application:
  name: @name@
  version: @version@

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ${application.name}
  data:
    mongodb:
      database: frota_znh
      host: localhost

grpc:
  port: 6565

logging:
  path: log
  maxHistory: 30
  fileSize: 1MB

hazelcast:
  cache-instances:
    - localhost:5701

copiloto-led:
  minutos-de-iluminacao: 2
  redis:
    host: localhost
    porta: 6379

planejamento:
  minutos-de-tolerancia: 1

