application:
  name: @name@
  version: @version@

spring:
  datasource:
    url: jdbc:mysql://mysql-hml:3306/frota_znh
    username: frota
    password: frota
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ${application.name}
  data:
    mongodb:
      database: frota_znh
      host: localhost

grpc:
  port: 6565

logging:
  path: log
  maxHistory: 30
  fileSize: 1MB

hazelcast:
  instances:
    - localhost:5701

redis:
  host: localhost
  porta: 6379

logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG